INSERT INTO ROOM (Room_ID, Floor_No, Secured, Bed_Type, Equipment_Available, Vacancy) Values(01, 1, 'N', 'Orthopedic', 'Wheelchair,Hoist,Bed pan', 'Y');
INSERT INTO ROOM (Room_ID, Floor_No, Secured, Bed_Type, Equipment_Available, Vacancy) Values(16, 2, 'N', 'Standard', 'Commode,Hoist,Call Bell', 'N');
INSERT INTO ROOM (Room_ID, Floor_No, Secured, Bed_Type, Equipment_Available, Vacancy) Values(03, 1, 'N', 'Orthopedic', 'Wheelchair,Hoist,Commode', 'N');
INSERT INTO ROOM (Room_ID, Floor_No, Secured, Bed_Type, Equipment_Available, Vacancy) Values(07, 1, 'Y', 'Standard', 'Wheelchair,Commode,Hoist', 'N');
INSERT INTO ROOM (Room_ID, Floor_No, Secured, Bed_Type, Equipment_Available, Vacancy) Values(17, 2, 'N', 'Orthopedic', 'Wheelchair,Hoist', 'N');
INSERT INTO ROOM (Room_ID, Floor_No, Secured, Bed_Type, Equipment_Available, Vacancy) Values(21, 2, 'N', 'Standard', 'Wheelchair,Hoist,Bed Pan', 'N');
INSERT INTO ROOM (Room_ID, Floor_No, Secured, Bed_Type, Equipment_Available, Vacancy) Values(13, 2, 'N', 'Standard', 'Wheelchair,Commode', 'N');
INSERT INTO ROOM (Room_ID, Floor_No, Secured, Bed_Type, Equipment_Available, Vacancy) Values(10, 1, 'Y', 'Standard', 'Wheelchair,Hoist,Commode', 'N');
INSERT INTO ROOM (Room_ID, Floor_No, Secured, Bed_Type, Equipment_Available, Vacancy) Values(24, 2, 'N', 'Orthopedic', 'Wheelchair,BPMachine', 'N'); 
INSERT INTO ROOM (Room_ID, Floor_No, Secured, Bed_Type, Equipment_Available, Vacancy) Values(23, 2, 'N', 'Orthopedic', 'Wheelchair,Commode,Hoist', 'N');
INSERT INTO ROOM (Room_ID, Floor_No, Secured, Bed_Type, Equipment_Available, Vacancy) Values(19, 2, 'N', 'Orthopedic', 'Bed Pan, Hoist', 'N');
INSERT INTO ROOM (Room_ID, Floor_No, Secured, Bed_Type, Equipment_Available, Vacancy) Values(02, 1, 'N', 'Orthopedic', 'Wheelchair,Commode,', 'N');
INSERT INTO ROOM (Room_ID, Floor_No, Secured, Bed_Type, Equipment_Available, Vacancy) Values(09, 1, 'Y', 'Standard', 'Walking Frame,Commode', 'N');
INSERT INTO ROOM (Room_ID, Floor_No, Secured, Bed_Type, Equipment_Available, Vacancy) Values(18, 2, 'N', 'Standard', 'Wheelchair,Hoist', 'N');
INSERT INTO ROOM (Room_ID, Floor_No, Secured, Bed_Type, Equipment_Available, Vacancy) Values(04, 1, 'N', 'Standard', 'Walking Frame,Commode', 'N');
INSERT INTO ROOM (Room_ID, Floor_No, Secured, Bed_Type, Equipment_Available, Vacancy) Values(05, 1, 'Y', 'Standard', 'Wheelchair,Commode,Hoist', 'N');
INSERT INTO ROOM (Room_ID, Floor_No, Secured, Bed_Type, Equipment_Available, Vacancy) Values(06, 1, 'Y', 'Standard', 'Wheelchair,Bed Pan,Hoist', 'Y');
INSERT INTO ROOM (Room_ID, Floor_No, Secured, Bed_Type, Equipment_Available, Vacancy) Values(08, 1, 'Y', 'Orthopedic', 'Wheelchair,Bed Pan,Hoist', 'Y');
INSERT INTO ROOM (Room_ID, Floor_No, Secured, Bed_Type, Equipment_Available, Vacancy) Values(11, 1, 'Y', 'Orthopedic', 'Wheelchair,Bed Pan,Hoist', 'N');
INSERT INTO ROOM (Room_ID, Floor_No, Secured, Bed_Type, Equipment_Available, Vacancy) Values(12, 1, 'Y', 'Standard', 'Walking Frame,Commode', 'Y');
INSERT INTO ROOM (Room_ID, Floor_No, Secured, Bed_Type, Equipment_Available, Vacancy) Values(14, 2, 'N', 'Standard', 'Wheelchair,Commode,', 'N');
INSERT INTO ROOM (Room_ID, Floor_No, Secured, Bed_Type, Equipment_Available, Vacancy) Values(15, 2, 'N', 'Orthopedic', 'Wheelchair,BP Machine,Bed Pan', 'N');
INSERT INTO ROOM (Room_ID, Floor_No, Secured, Bed_Type, Equipment_Available, Vacancy) Values(20, 2, 'N', 'Standard', 'Walking Frame,Commode', 'Y');
INSERT INTO ROOM (Room_ID, Floor_No, Secured, Bed_Type, Equipment_Available, Vacancy) Values(22, 2, 'N', 'Standard', 'Wheelchair,BP Machine,IV Stand', 'Y');
INSERT INTO ROOM (Room_ID, Floor_No, Secured, Bed_Type, Equipment_Available, Vacancy) Values(25, 2, 'N', 'Orthopedic', 'Wheelchair, Hoist, Bed Pan', 'Y');